### ISSUE TITLE
Apple II GS won't load

### ISSUE THREAD

**Issue by mcfilmmakers** [xinyingho/Negatron#2]
Negatron doesn't show the Apple II GS software lists. It will only show the regular Apple II lists.

The missing lists are:
apple2gs
apple2gs_flop_misc
apple2gs_flop_orig

NegaMAME shows and plays these lists as expected but they don't appear in Negatron when using the AppleIIgs machines.

Please fix.

**Comment by xinyingho** [comment]
By default, the machine is configured to get 4 floppy drives: the 2 first can only fit 5.25" floppy disks while the 2 others are about 3.5" floppy disks. Apple II GS dedicated disks have only been released as 3.5" floppy disks so you can find the II GS games in the 2 software lists only in the 2 3.5" floppy drives.

**Comment by mcfilmmakers** [comment]
Oh, I see! In that case, I suggest making it more obvious to the end user somehow...
